wc:
  mp:
    token: ""
    secret: ""
    encoding_aes_key: ""


mysqls:
  -
    host: "127.0.0.1"
    port: "3306"
    db-name: "snoopy"
    username: "root"
    password: "123456"
    conn: "root:123456@tcp(127.0.0.1:3306)/snoopy?charset=utf8mb4&parseTime=True&loc=Local"
  
  -
    host: "127.0.0.1"
    port: "3306"
    db-name: "test"
    username: "root"
    password: "123456"
    conn: "root:123456@tcp(127.0.0.1:3306)/snoopy?charset=utf8mb4&parseTime=True&loc=Local"

log:
  log_level: "debug"
  log_format: ""
  log_path: "./logs"
  log_file_name: "logs.log"
  log_file_max_size: 5
  log_file_max_backups: 10
  log_max_age: 10
  log_compress: false
  log_stdout: true

jaeger:
  collectorEndpoint: "http://127.0.0.1:14268/api/traces"
  localAgentHostPort: "http://127.0.0.1:6831"
  ServiceName: "snoopy global trace"

minio:
  endpoint: "127.0.0.1:6312"
  accessKeyID: "1EMigCJcWUfoNFaaIrf4"
  secretAccessKey: "TKFtQFcf0Jt6Fndc5B3cw9ifsfiqkmWos9ceWgrg"
